spring.application.name=user-service

server.port=8080
server.servlet.context-path=/user-service
server.error.include-stacktrace=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=create


spring.cloud.gateway.discovery.locator.enabled=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.should-fetch-registry=true
#eureka.instance.hostname=user-service



# JWT Configuration
security.jwt.secret-key=f77109f4bc6a501e1ef2283c3a18ccd4e0054990e71d42294615c4c30ef755fc

# 15min in millisecond
security.jwt.expiration-time=90000000
# 7 days
security.jwt.refresh-expiration-time=604800000 

#token types
security.jwt.access-token-type = access
security.jwt.refresh-token-type = refresh

#jwt.secret=your_jwt_secret
#jwt.expiration.ms=3600000 # 1 hour in milliseconds


logging.level.org.springframework.web=DEBUG
logging.level.root=ERROR
logging.level.org.hibernate= DEBUG
logging.level.app.g_agent.user_service=DEBUG

#spring.security.oauth2.resourceserver.jwt.issuer-uri = https://example.com/oauth2/default
spring.security.oauth2.authorizationserver.issuer = http://auth-server:9000


spring.security.oauth2.authorizationserver.client.oidc-client.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-authentication-methods="client_secret_basic"
spring.security.oauth2.authorizationserver.client.oidc-client.registration.client-id=oidc-client
spring.security.oauth2.authorizationserver.client.oidc-client.registration.post-logout-redirect-uris=http://127.0.0.1:8080/
spring.security.oauth2.authorizationserver.client.oidc-client.registration.redirect-uris=http://127.0.0.1:8080/login/oauth2/code/oidc-client
spring.security.oauth2.authorizationserver.client.oidc-client.registration.scopes=openid,profile
spring.security.oauth2.authorizationserver.client.oidc-client.require-authorization-consent=true
spring.security.user.name=user
spring.security.user.password=password

#turn off in production
spring.mvc.log-request-details=true
spring.codec.log-request-details=true  


#spring forward error to our handler

server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always

#hibernate to use UTC
spring.jpa.hibernate.jdbc.time_zone=UTC


